name: CI
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install yarn -g
      - run: yarn install
      - name: Build Scan
        run: yarn run scan:build
      - name: Test Scan
        run: yarn run scan:test