name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: run scan:build # will run `yarn build` command
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: run scan:test # will run `yarn test` command